feat: :sparkles: Add caddy client_ip variable parsing
corazawaf/coraza-caddy pull request #184
Opened 2024-12-17 01:10 UTC by adrienyhuel

Resolve #150

2024-12-18 11:42 UTC, fzipi reviewed
Thanks for your contribution!

Is there a simple way to add tests on this change?

2024-12-18 12:51 UTC, adrienyhuel commented
@fzipi 
I don't know how we could test that, it's only in the logs

2024-12-18 15:24 UTC, fzipi requested changes
Indentation on this code is bad. Maybe try to run `go fmt`?

Also, this might just deserve a new function call instead of adding it here?

2024-12-18 16:36 UTC, adrienyhuel commented
@fzipi 
A function that might include the whole address parsing (from req.RemoteAddr and caddy client_ip variable) ?

2024-12-19 13:43 UTC, fzipi commented
I think it is way more clear now. @M4tteoP can you help me with the review?

2025-01-08 08:57 UTC, jcchavezs commented
Thanks for this @adrienyhuel. I think the unit tests here aren't enough to cover this. Any chance you can create an integration test using `caddytest` package as in https://github.com/dunglas/frankenphp/blob/2b7b3d1e4b0bb2634936ce463ffe7cf10c5978e3/caddy/caddy_test.go#L18. It can live in `coraza_test.go` file.

2025-01-08 12:01 UTC, adrienyhuel commented
@jcchavezs I added a simple integration test, is it sufficient ?

2025-01-08 19:34 UTC, jcchavezs commented on coraza_test.go
> +    time.Sleep(1 * time.Second)
wonder why we need this?

2025-01-08 19:36 UTC, jcchavezs commented
Please fix the lint and we can merge it.

2025-01-08 20:05 UTC, adrienyhuel commented
@jcchavezs my bad, I always forget to lint as my IDE always replace tabs with 4 spaces...

2025-01-08 20:08 UTC, fzipi commented
Maybe adding an `.editorconfig` could help in this repo for that case?

2025-01-08 21:46 UTC, M4tteoP submitted a review, later dismissed
Sorry, I'm a bit late, I'm finally taking a look. Overall looks good to me!

2025-01-08 21:46 UTC, M4tteoP commented on test.init.config
> +        trusted_proxies static private_ranges
Would it be possible to add a comment on why this line is needed? Also, is it then something that is strictly required to have the client_ip properly working? If so, should we document it in the readme: https://github.com/corazawaf/coraza-caddy?tab=readme-ov-file#plugin-syntax?

2025-01-08 21:58 UTC, adrienyhuel commented on test.init.config
> +        trusted_proxies static private_ranges
@M4tteoP 
This line is needed is you want Caddy to populate client_ip from X-Forwarded-For header, in the case Caddy is behind a reverse proxy.
If you don't provide this config, Caddy will populate client_ip from request.RemoteAddr : 
- If client connect directly, it will be the real IP
- if client connect through another proxy (like Cloudflare, or an Ingress in K8s), it will the proxy IP
See : https://caddyserver.com/docs/caddyfile/options#trusted-proxies
I think all users who want real client IP in their access logs know that config.

2025-01-08 21:59 UTC, M4tteoP commented on test.init.config
> +        trusted_proxies static private_ranges
Awesome, thanks for the explanation!

2025-01-08 22:01 UTC, adrienyhuel commented on test.init.config
> +        trusted_proxies static private_ranges
Btw, with this pull request, coraza-caddy will use client_ip variable provided by caddy to use in WAF rules and in WAF logs, regardless of how Caddy populate this variable.

2025-01-08 22:34 UTC, jcchavezs commented on test.init.config
> +        trusted_proxies static private_ranges
@adrienyhuel please add this explanation as a comment in the config.

2025-01-08 22:49 UTC, adrienyhuel commented on test.init.config
> +        trusted_proxies static private_ranges
@jcchavezs done :)

2025-01-08 23:34 UTC, M4tteoP approved these changes

2025-01-09 09:10 UTC, jcchavezs approved these changes

2025-01-09 09:11 UTC, merged